name: iOS Beta Build

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XCodes
        run: |
          brew install xcodesorg/made/xcodes
          xcodes install 15.4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: |
          cd packages/mobile-app-did
          yarn install

      - name: Setup Environment
        run: yarn handle-network network-test1
        working-directory: packages/mobile-app-did

      # - name: Create Directory for ruby
      #   run: sudo mkdir /opt/hostedtoolcache && sudo chown -R runner:runner /opt/hostedtoolcache

      # Setup Ruby while Caching Gems
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Upgrade Bundler
        run: |
          gem install bundler
          bundle update --bundler
        working-directory: packages/mobile-app-did/ios

      # Install fastlane
      - name: Install Fastlane
        run: gem install fastlane
        working-directory: packages/mobile-app-did/ios

      - name: Bundle Install
        run: bundle install
        working-directory: packages/mobile-app-did/ios

      # - name: Build Android Release
      #   run: |
      #     cd packages/mobile-app-did
      #     yarn build:apk-test1

      - name: Build android release
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'build_ipa'
          subdirectory: packages/mobile-app-did/ios
