name: iOS Beta Build

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XCodes
        run: |
          brew install xcodesorg/made/xcodes
          xcodes install 15.4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: |
          cd packages/mobile-app-did
          yarn install

      - name: Create .env file
        run: |
          cp packages/mobile-app-did/.env.example packages/mobile-app-did/.env
          sed -i "s|PORT_KEY_CODE *=.*|PORT_KEY_CODE=${{ secrets.PORT_KEY_CODE }}|" packages/mobile-app-did/.env
          sed -i "s|BACKEND_PUBKEY *=.*|BACKEND_PUBKEY=${{ secrets.BACKEND_PUBKEY }}|" packages/mobile-app-did/.env
          sed -i "s|VERSION *=.*|VERSION=${{ secrets.VERSION }}|" packages/mobile-app-did/.env
          sed -i "s|COMMUNICATE_APP_PRIVITEKEY *=.*|COMMUNICATE_APP_PRIVITEKEY=${{ secrets.COMMUNICATE_APP_PRIVITEKEY }}|" packages/mobile-app-did/.env
          sed -i "s|RELEASE_STORE_FILE *=.*|RELEASE_STORE_FILE=${{ secrets.RELEASE_STORE_FILE }}|" packages/mobile-app-did/.env
          sed -i "s|RELEASE_KEY_ALIAS *=.*|RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}|" packages/mobile-app-did/.env
          sed -i "s|RELEASE_STORE_PASSWORD *=.*|RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}|" packages/mobile-app-did/.env
          sed -i "s|RELEASE_KEY_PASSWORD *=.*|RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}|" packages/mobile-app-did/.env
          sed -i "s|LOCAL_STORE_FILE *=.*|LOCAL_STORE_FILE=${{ secrets.LOCAL_STORE_FILE }}|" packages/mobile-app-did/.env
          sed -i "s|GOOGLE_WEB_CLIENT_ID *=.*|GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID }}|" packages/mobile-app-did/.env
          sed -i "s|GOOGLE_IOS_CLIENT_ID *=.*|GOOGLE_IOS_CLIENT_ID=${{ secrets.GOOGLE_IOS_CLIENT_ID }}|" packages/mobile-app-did/.env
          sed -i "s|GOOGLE_ANDROID_CLIENT_ID *=.*|GOOGLE_ANDROID_CLIENT_ID=${{ secrets.GOOGLE_ANDROID_CLIENT_ID }}|" packages/mobile-app-did/.env

      - name: Setup Environment
        run: yarn handle-network network-test1
        working-directory: packages/mobile-app-did

      # - name: Create Directory for ruby
      #   run: sudo mkdir /opt/hostedtoolcache && sudo chown -R runner:runner /opt/hostedtoolcache

      # Setup Ruby while Caching Gems
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      # Install fastlane
      - name: Install Fastlane
        run: gem install fastlane
        working-directory: packages/mobile-app-did/ios

      - name: Bundle Install
        run: bundle install
        working-directory: packages/mobile-app-did/ios

      # - name: Build Android Release
      #   run: |
      #     cd packages/mobile-app-did
      #     yarn build:apk-test1

      - name: Build android release
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'build_ipa'
          subdirectory: packages/mobile-app-did/ios
